version: "3.10"
services:
  db:
    image: postgres:15
    container_name: db
    command: -p 5433
    expose:
      - 5433
    env_file:
      - .env-non-dev
    volumes:
    - sm_app-db-data:/var/lib/postgresql/data


  app:
    build:
      context: .
    environment:
      - PYTHONPATH=/sm_app/simple_messager
    env_file:
      - .env-non-dev
    container_name: sm_app
    ports:
      - 8000:8000
    command: ["/sm_app/.docker/app.sh"]
    depends_on:
      - db

volumes:
  sm_app-db-data:
    name: sm_app-db-data

