version: "3.7"
services:

  db:
    image: postgres:15
    container_name: db_itworkin
    command: -p 5435
    expose:
      - 5435
    env_file:
      - .env-non-dev
    volumes:
    - sm_app-db-data:/var/lib/postgresql/data


  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: sm_app
    ports:
      - 80:8000
    command: ["/sm_app/.docker/app.sh"]
    depends_on:
      - db

volumes:
  sm_app-db-data:
    name: sm_app-db-data

